name: Build bielarmorsweap
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract zip files
      run: unzip -o 0.zip
        
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Grant execute permission
      run: chmod +x gradlew
      
    - name: Build Minecraft Mod
      run: ./gradlew build --no-daemon
      
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: bielarmorsweap-jar
        path: build/libs/*.jar

